### ISSUE TITLE
`shot` Screenshot not generated even tho androidTest is passed.

### ISSUE THREAD

**Issue by wiryadev** [sergio-sastre/Android-screenshot-testing-playground#20]
I tried to run the shot test for both `lazycolumn` and `recyclerview` screen but there is no generated screenshot for both the record and the verification.
![image](https://user-images.githubusercontent.com/26060382/215645845-73e6ffe4-63b2-42da-b3b0-cb778b09f5d2.png)
I checked the screenshot folder and it is empty too.
![image](https://user-images.githubusercontent.com/26060382/215647132-ec5440a2-7796-449e-b36d-69a80cc9862e.png)

The report also shows 0 tests executed.
![image](https://user-images.githubusercontent.com/26060382/215646361-03d3fe56-4765-42e8-ba58-be799b1e2f13.png)
![image](https://user-images.githubusercontent.com/26060382/215646243-f307ae11-3286-4ed8-9011-1a86ad70cc7f.png)

The test shows up and report from `androidTest` directory confirm that.
![image](https://user-images.githubusercontent.com/26060382/215646799-6161b5c0-643e-441c-bf4d-7289b9abd5ee.png)

How to solve this or did i miss something?

**Comment by sergio-sastre** [comment]
I think that is coz I did not configured the sharedId as stated in Shot documentation.

It seems to be needed for some APIs.
Could you tell me the API of the emulator on which you are running the screenshot tests?

I’ll definitely update it if that is the case.
Also please try with another API.

Moreover, what OS is your machine running? MacOs, Windows or Linux?

**Comment by wiryadev** [comment]
I was trying with Pixel 4 XL API 31 using Windows. I havent tested it against another API yet.

**Comment by sergio-sastre** [comment]
> I was trying with Pixel 4 XL API 31 using Windows. I havent tested it against another API yet.

I've checked it on my Mac and it works.
I'm afraid it has to do with Shot & Windows playing together.

Theoretically, it should not happen on emulators running API 27 or lower.
Could you please confirm that it works on API <28?

**Comment by sergio-sastre** [comment]
@wiryadev 
I have one more idea why they might not show up. 
could you try running this before the screenshots?

`adb shell settings put global hidden_api_policy 1`

If that works, there is a way I could fix it without requiring you to run that on emulators before running screenshots with shot

**Comment by sergio-sastre** [comment]
Close due to inactivity
@wiryadev feel free to reopen it if still happening with the newest examples
