### ISSUE TITLE
Add a sample using robolectric native graphics

### ISSUE THREAD

**Issue by yschimke** [sergio-sastre/Android-screenshot-testing-playground#22]
Now possible with https://github.com/robolectric/robolectric/releases/tag/robolectric-4.10-alpha-1

> Robolectric 4.10 adds support for native Android graphics. It is currently disabled by default and can be enabled using @GraphicsMode(NATIVE). When native graphics is enabled, interactions with Android graphics classes use real native Android graphics code and are much higher fidelity.

**Comment by sergio-sastre** [comment]
> @yschimke
> Sure! It’s in my TODO list once back from holidays

Roborazzi Tests already merged :)
